stages:
  - test
  - deploy

variables:
  DJANGO_SETTINGS_MODULE: "backend.settings"
  VIRTUAL_ENV: "/builds/project-0/src/backend/venv"

image: python:3.10.12

before_script:
  - |
    python -m venv venv
    source venv/bin/activate
    pip install --upgrade pip
    pip install wheel
    pip install -r src/backend/requirements.txt
    pip install -r src/sentiment_analysis/requirements.txt

backend_test:
  stage: test
  script:
    - cd src/backend/
    - |
      export PYTHONPATH=src/backend:$PYTHONPATH
      python manage.py test

frontend_test: # job name - for mobile react native tests
  stage: test
  image: node:latest
  before_script:
    - cd src/mobile_react_native/forknfind-mobile
    - npm install
  script:
    - npm test

sent_analysis_test: # job name - for sentiment analysis tests
  stage: test
  image: python:3.10.12
  before_script:
    - cd src/sentiment_analysis/
    - pip install -r requirements.txt
  script:
    - python3 tests_sentiment_analysis.py

heroku_deploy:
  stage: deploy
  image: ruby:3.3
  before_script:
    - gem install dpl
  script:
    - cd src/backend
    - dpl --provider=heroku --app=HEROKU_APP_NAME --api-key=$HEROKU_API_KEY
  only:
    - master