stages:
  - build
  - test

variables:
  DJANGO_SETTINGS_MODULE: "backend.settings"
  VIRTUAL_ENV: "/builds/project-0/src/backend/venv"

build_python:
  stage: build
  image: python:3.10.12
  before_script:
    - python -m venv venv
    - source venv/bin/activate
    - pip install --upgrade pip
    - pip install wheel
    - pip install -r src/sentiment_analysis/requirements.txt
    - pip install -r src/backend/requirements.txt
  script:
    - echo "Python environment setup"


backend_test:
  stage: test
  image: python:3.10.12
  script:
    - source venv/bin/activate
    - cd src/backend/
    - export PYTHONPATH=src/backend:$PYTHONPATH
    - python manage.py test

sent_analysis_test:
  stage: test
  image: python:3.10.12
  script:
    - source venv/bin/activate
    - python3 tests_sentiment_analysis.py