variables:
  DJANGO_SETTINGS_MODULE: "backend.settings"
  VIRTUAL_ENV: "/builds/project-0/src/backend/venv"

image: python:3.10.12

before_script:
  - |
    python -m venv venv
    source venv/bin/activate
    pip install --upgrade pip
    pip install wheel
    pip install -r src/backend/requirements.txt

test:
  script:
    - cd src/backend/
    - |
      export PYTHONPATH=src/backend:$PYTHONPATH
      python manage.py test