# Generated by Django 3.2.12 on 2023-12-28 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forknfind', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Restaurant',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('google_id', models.CharField(default='', max_length=100)),
                ('longitude', models.FloatField()),
                ('latitude', models.FloatField()),
                ('name', models.CharField(default='', max_length=100)),
                ('average_rating', models.FloatField()),
            ],
        ),
    ]
