# Generated by Django 3.2.12 on 2024-01-02 14:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('forknfind', '0006_auto_20240102_1436'),
    ]

    operations = [
        migrations.AlterField(
            model_name='restaurantday',
            name='close_time',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='close_time', to='forknfind.restauranttime'),
        ),
        migrations.AlterField(
            model_name='restaurantday',
            name='open_time',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='open_time', to='forknfind.restauranttime'),
        ),
        migrations.AlterField(
            model_name='restauranttime',
            name='hour',
            field=models.IntegerField(choices=[(0, 0), (1, 1), (2, 2), (3, 3), (4, 4), (5, 5), (6, 6), (7, 7), (8, 8), (9, 9), (10, 10), (11, 11), (12, 12), (13, 13), (14, 14), (15, 15), (16, 16), (17, 17), (18, 18), (19, 19), (20, 20), (21, 21), (22, 22), (23, 23)]),
        ),
    ]
