# Generated by Django 3.2.12 on 2024-01-02 19:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('forknfind', '0007_auto_20240102_1441'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurant',
            name='hours',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='forknfind.restauranthours'),
            preserve_default=False,
        ),
    ]
