# Generated by Django 3.2.12 on 2024-01-02 19:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('forknfind', '0008_restaurant_hours'),
    ]

    operations = [
        migrations.AlterField(
            model_name='restaurant',
            name='hours',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='forknfind.restauranthours'),
        ),
    ]
