# Generated by Django 3.2.12 on 2024-01-13 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forknfind', '0009_alter_restaurant_hours'),
    ]

    operations = [
        migrations.CreateModel(
            name='HybridRecommender',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('test', models.TextField()),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
