# Generated by Django 3.2.12 on 2024-01-13 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forknfind', '0010_hybridrecommender'),
    ]

    operations = [
        migrations.AddField(
            model_name='hybridrecommender',
            name='collaborative_model',
            field=models.BinaryField(default=b''),
            preserve_default=False,
        ),
    ]
