# Generated by Django 3.2.12 on 2024-01-13 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forknfind', '0011_hybridrecommender_collaborative_model'),
    ]

    operations = [
        migrations.AddField(
            model_name='hybridrecommender',
            name='content_model',
            field=models.BinaryField(default=b''),
            preserve_default=False,
        ),
    ]
