# Generated by Django 3.2.12 on 2024-01-13 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forknfind', '0012_hybridrecommender_content_model'),
    ]

    operations = [
        migrations.AddField(
            model_name='hybridrecommender',
            name='restaurant_id_masking',
            field=models.TextField(default='Hi'),
            preserve_default=False,
        ),
    ]
