# Generated by Django 5.0.1 on 2024-01-17 17:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forknfind', '0013_hybridrecommender_restaurant_id_masking'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hybridrecommender',
            name='test',
        ),
    ]
