# Generated by Django 4.1 on 2024-02-05 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forknfind', '0016_review_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurant',
            name='review_number',
            field=models.IntegerField(default=0),
        ),
    ]
