# Generated by Django 5.0.1 on 2024-03-29 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forknfind', '0017_restaurant_review_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='sentiment',
            field=models.IntegerField(choices=[(1, 1), (2, 2)], default=0),
        ),
    ]
