# Generated by Django 5.0.1 on 2024-03-29 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forknfind', '0018_review_sentiment'),
    ]

    operations = [
        migrations.CreateModel(
            name='SentimentAnalysis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sentiment_model', models.BinaryField()),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
